import React from 'react';
import Page from '../components/Page';

const privacy = () => {
	return (
		<Page title="Privacy Policy | Vicnent's Sphere">
			<div className='terms'>
				<h1 style={{ marginTop: 0 }}>PRIVACY POLICY</h1>
				<p>Last updated: Jun 01, 2021</p>
				<p>
					This Privacy Policy describes Our policies and procedures on the
					collection, use and disclosure of Your information when You use the
					Service and tells You about Your privacy rights and how the law
					protects You. We use Your Personal data to provide and improve the
					Service. By using the Service, You agree to the collection and use of
					information in accordance with this Privacy Policy.
				</p>
				<h3>Interpretation</h3>
				<p>
					The words of which the initial letter is capitalized have meanings
					defined under the following conditions. The following definitions
					shall have the same meaning regardless of whether they appear in
					singular or in plural.
				</p>
				<h3>Definitions</h3>
				<p>For the purposes of this Privacy Policy:</p>
				<p>
					<strong>Account</strong> means a unique account created for You to
					access our Service or parts of our Service.
				</p>
				<p>
					<strong>Organization </strong>(referred to as either "the
					Organization", "We", "Us" or "Our" in this Agreement) refers to
					Vincent's Sphere.
				</p>
				<p>
					<strong>Cookies</strong> are small files that are placed on Your
					computer, mobile device or any other device by a website, containing
					the details of Your browsing history on that website among its many
					uses.
				</p>
				<p>
					<strong>Device</strong> any device that can access the Service such as
					a computer, a cellphone or a digital tablet.
				</p>
				<p>
					<strong>Personal Data</strong>
					 is any information that relates to an identified or identifiable
					individual.
				</p>
				<p>
					<strong>Service</strong> refers to the Website.
				</p>
				<p>
					<strong>Service Provider</strong>
					 means any natural or legal person who processes the data on behalf of
					the Organization. It refers to third-party organizations or
					individuals employed by the Organization to facilitate the Service, to
					provide the Service on behalf of the Organization, to perform services
					related to the Service or to assist the Organization in analyzing how
					the Service is used.
				</p>
				<p>
					<strong>Usage Data</strong>
					 refers to data collected automatically, either generated by the use
					of the Service or from the Service infrastructure itself (for example,
					the duration of a page visit).
				</p>
				<p>
					<strong>Website</strong>
					 refers to Vincent's Sphere, accessible from 
					<a href='https://vincentsphere.com'>https://vincentsphere.com</a>
				</p>
				<p>
					<strong>You</strong> means the individual accessing or using the
					Service, or the organization, or other legal entity on behalf of which
					such individual is accessing or using the Service, as applicable.
				</p>
				<h1>Collection and Usage of Data</h1>
				<h2>Types of Data Collected</h2>
				<h3>Personal Data</h3>
				<p>
					Name <br /> Email Address <br /> Phone Number <br /> Usage Data
				</p>
				<h3>Usage Data</h3>
				<p>
					Usage Data may include information such as Your Device's Internet
					Protocol address (e.g. IP address), browser type, browser version, the
					pages of our Service that You visit, the time and date of Your visit,
					the time spent on those pages, unique device identifiers and other
					diagnostic data.
				</p>
				<p>
					When You access the Service by or through a mobile device, We may
					collect certain information automatically, including the type of
					mobile device You use, Your mobile device unique ID, the IP address of
					Your mobile device, Your mobile operating system, the type of mobile
					Internet browser You use, unique device identifiers and other
					diagnostic data. We may also collect information that Your browser
					sends whenever You visit our Service or when You access the Service by
					or through a mobile device.
				</p>
				<h3>Cookies</h3>
				<p>
					We may use Cookies and similar technologies to track the activity on
					Our Service and store certain information. The technologies We use may
					include:
				</p>
				<p>
					<strong>Cookies or Browser Cookies:</strong>
					 A cookie is a small file placed on Your Device. You can instruct Your
					browser to refuse all Cookies or to indicate when a Cookie is being
					sent. However, if You do not accept Cookies, You may not be able to
					use some parts of our Service. Unless you have adjusted Your browser
					setting so that it will refuse Cookies, our Service may use Cookies.
					Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies
					remain on Your personal computer or mobile device when You go offline,
					while Session Cookies are deleted as soon as You close Your web
					browser.
				</p>
				<p>
					<strong>Purpose: </strong>
					These Cookies allow us to remember choices You make when You use the
					Website. The purpose of these Cookies is to provide You with a more
					personal experience and to avoid You having to re-enter your
					preferences every time You use the Website.
				</p>
				<h3>Use of Your Personal Data</h3>
				<p>
					The organization may use Personal Data for the following purposes: To
					provide and maintain our Service, including to monitor the usage of
					our Service. To contact You: To contact You by email regarding updates
					or informative communications related to the functionalities, events
					or contracted services, including the security updates, when necessary
					or reasonable for their implementation.
				</p>
				<p>
					To provide You with news, special offers and general information about
					other services and events which we offer unless You have opted not to
					receive such information.
				</p>
				<p>
					To manage Your requests: To attend and manage Your requests to Us.
				</p>
				<p>
					For other purposes: We may use your information for other purposes,
					such as data analysis, identifying usage trends, determining the
					effectiveness of our promotional campaigns and to evaluate and improve
					our Service
				</p>
				<h2>Disclosure of Your Personal Data</h2>
				<h3>Law enforcement</h3>
				<p>
					Under certain circumstances, the organization may be required to
					disclose Your Personal Data if required to do so by law or in response
					to valid requests by public authorities (e.g. a court or a government
					agency).
				</p>
				<h3>Other legal requirements</h3>
				<p>
					The organization may disclose Your Personal Data in the good faith
					belief that such action is necessary to: <br />
					Comply with a legal obligation
					<br /> Protect and defend the rights or property of the organization
					<br />
					Prevent or investigate possible wrongdoing in connection with the
					Service <br /> Protect the personal safety of Users of the Service or
					the public <br />
					Protect against legal liability
				</p>
				<h3>Links to Other Websites</h3>
				<p>
					Our Service may contain links to other websites that are not operated
					by Us. If You click on a third party link, You will be directed to
					that third party's site. We strongly advise You to review the Privacy
					Policy of every site You visit.
				</p>
				<p>
					We have no control over and assume no responsibility for the content,
					privacy policies or practices of any third party sites or services.
				</p>
				<h3>Changes to this Privacy Policy</h3>
				<p>
					We may update Our Privacy Policy from time to time. We will notify You
					of any changes by posting the new Privacy Policy on this page.
				</p>
				<p>
					We will let You know via email and/or a prominent notice on Our
					Service, prior to the change becoming effective and update the "Last
					updated" date at the top of this Privacy Policy.
				</p>
				<p>
					You are advised to review this Privacy Policy periodically for any
					changes. Changes to this Privacy Policy are effective when they are
					posted on this page.
				</p>
				<h3>Contact Us</h3>
				<p>
					If you have any questions about this Privacy Policy, You can contact
					us:
				</p>
				<p>
					<strong>
						By email:  <a>support@vincentsphere.com</a>
					</strong>
				</p>
			</div>
		</Page>
	);
};

export default privacy;
